### ISSUE TITLE
Search result not in relevant order

### ISSUE THREAD

**Issue by swell-d** [mageworx/search-suite-autocomplete#11]
Thank you guys for the great module! 
Could you please help me. Quick search returned me the product list not in the same order if i click "enter" and see the search result page. How can i fix it? 
I want to see in quick search products sorted by "relevance". 
I use Magento 2.3.4, MySQL search engine.

**Comment by sergei-sss** [comment]
Hello @swell-d , we briefly checked this case locally but we could not reproduce it. Please submit a support ticket here  https://www.mageworx.com/support and our team will help you.

**Comment by swell-d** [comment]
Thanks @sergei-sss, i send the ticket. 

P.S. You can see the problem here: https://soldering24.ru/ try "888d" for example.

**Comment by sergei-sss** [comment]
@swell-d we have update the extension, please check and close this issue if it works for you.

**Comment by swell-d** [comment]
Hello @sergei-sss 
thanks for your help. I tried the new one Product.php, but unfortunately it not works in my website. 
I tried add "ASC" and "DESC" sort direction and all time had the same search result. 
Finally, I despaired and turned Elasticsearch back on. With Elasticsearch it works as i want.
