### ISSUE TITLE
Anyway to force AND instead of OR query

### ISSUE THREAD

**Issue by ahdee** [mageworx/search-suite-autocomplete#14]
Hi, when I search for "bird food" the results that shows up would display all products with the keyword bird OR food so that fish food would also show up.  My question is: is there anyway to force the search to use AND instead of OR?  thanks!

**Comment by sergei-sss** [comment]
Hi @ahdee, 
Thank you for this suggestion. However, our Search AutoComplete solution doesn’t add its own search algorithms. We use the results retrieved from the native Magento 2 search. You should try to find solution for your current search engine: built-in search engine or elastic search.
