### ISSUE TITLE
Conflict with Mageplaza Layered navigation

### ISSUE THREAD

**Issue by manikumaran1978** [mageworx/search-suite-autocomplete#15]
When used with this extension there is error as below
https://www.mageplaza.com/magento-2-layered-navigation-extension/

{"0":"Sorry, something went wrong. You can find out more in the error log.","1":"#1 Magento\\Framework\\Data\\Collection\\AbstractDb->_renderFilters() called at [app\/code\/Mageplaza\/LayeredNavigation\/Model\/ResourceModel\/Fulltext\/Collection.php:519]\n#2 Mageplaza\\LayeredNavigation\\Model\\ResourceModel\\Fulltext\\Collection->_renderFilters() called at [vendor\/magento\/module-eav\/Model\/Entity\/Collection\/AbstractCollection.php:923]\n#3 Magento\\Eav\\Model\\Entity\\Collection\\AbstractCollection->load() called at [vendor\/magento\/module-catalog\/Model\/ResourceModel\/Product\/Collection.php:832]\n#4 Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection->load() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#5 Mageplaza\\LayeredNavigation\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#6 Mageplaza\\LayeredNavigation\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#7 Mageplaza\\LayeredNavigation\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->___callPlugins() called at [generated\/code\/Mageplaza\/LayeredNavigation\/Model\/ResourceModel\/Fulltext\/Collection\/Interceptor.php:39]\n#8 Mageplaza\\LayeredNavigation\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->load() called at [vendor\/magento\/framework\/Data\/Collection.php:839]\n#9 Magento\\Framework\\Data\\Collection->getIterator() called at [app\/code\/MageWorx\/SearchSuiteAutocomplete\/Model\/Search\/Product.php:85]\n#10 MageWorx\\SearchSuiteAutocomplete\\Model\\Search\\Product->getResponseData() called at [app\/code\/MageWorx\/SearchSuiteAutocomplete\/Model\/Search.php:48]\n#11 MageWorx\\SearchSuiteAutocomplete\\Model\\Search->getData() called at [app\/code\/MageWorx\/SearchSuiteAutocomplete\/Controller\/Ajax\/Index.php:76]\n#12 MageWorx\\SearchSuiteAutocomplete\\Controller\\Ajax\\Index->execute() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#13 MageWorx\\SearchSuiteAutocomplete\\Controller\\Ajax\\Index\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#14 MageWorx\\SearchSuiteAutocomplete\\Controller\\Ajax\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/App\/Action\/Plugin\/ActionFlagNoDispatchPlugin.php:51]\n#15 Magento\\Framework\\App\\Action\\Plugin\\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#16 MageWorx\\SearchSuiteAutocomplete\\Controller\\Ajax\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#17 MageWorx\\SearchSuiteAutocomplete\\Controller\\Ajax\\Index\\Interceptor->___callPlugins() called at [generated\/code\/MageWorx\/SearchSuiteAutocomplete\/Controller\/Ajax\/Index\/Interceptor.php:26]\n#18 MageWorx\\SearchSuiteAutocomplete\\Controller\\Ajax\\Index\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:111]\n#19 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#20 MageWorx\\SearchSuiteAutocomplete\\Controller\\Ajax\\Index\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#21 MageWorx\\SearchSuiteAutocomplete\\Controller\\Ajax\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#22 MageWorx\\SearchSuiteAutocomplete\\Controller\\Ajax\\Index\\Interceptor->___callPlugins() called at [generated\/code\/MageWorx\/SearchSuiteAutocomplete\/Controller\/Ajax\/Index\/Interceptor.php:39]\n#23 MageWorx\\SearchSuiteAutocomplete\\Controller\\Ajax\\Index\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:186]\n#24 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:118]\n#25 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#26 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#27 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php:99]\n#28 Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#29 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:71]\n#30 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#31 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#32 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#33 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#34 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:263]\n#35 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]\n","url":"\/MageWorx_searchsuiteautocomplete\/ajax\/index\/?q=salad&_=1604926251278","script_name":"\/index.php","report_id":"445cc10879d3788a24b408b758c480dcbddd11c4659fd3e6e4d5b9682d6856fa"}

**Comment by vitaliddd** [comment]
Hello,
Please contact our support team and they will investigate this conflict.

**Comment by AndyJAllen** [comment]
I get this same error.

MageWorx SearchSuiteAutocomplete 2.1.11
Newest version of Porto theme which comes with LayeredNavigation
Magento 2.3.7
PHP 7.4
ElasticSearch 7.13.4

**Comment by sergei-sss** [comment]
@AndyJAllen We'll check it shortly.

**Comment by Kerolusnasser** [comment]
i have solved this issue by changing this line in app/code/Mageplaza/LayeredNavigation/Model/ResourceModel/Fulltext/Collection.php
from 
`if ($this->request->getFullActionName() === 'catalogsearch_result_index') {`
to
`if ($this->request->getFullActionName() === 'catalogsearch_result_index' || strtolower($this->request->getFullActionName()) === 'mageworx_searchsuiteautocomplete_ajax_index') {`

Now it's working :)
