### ISSUE TITLE
Problem in displaying HTML Character Entities

### ISSUE THREAD

**Issue by joshwyrick** [mageworx/search-suite-autocomplete#2]
There appears to a problem displaying HTML special characters or entities in the suggestion results. See attached. 

![special-chars](https://user-images.githubusercontent.com/12661899/54926233-40e98080-4ee6-11e9-85e1-d693da0af4c3.png)

I also found that these types of characters are being converted to the special codes for display, even if the product name/description data has the actual characters and not the entity codes.

**Comment by sergei-sss** [comment]
@joshwyrick We've fixed it, thank you for the report.
