### ISSUE TITLE
Doesn't work with ElasticSearch

### ISSUE THREAD

**Issue by AndyJAllen** [mageworx/search-suite-autocomplete#4]
FYI -- not working with Magento 2.3.1 and ElasticSearch 6.

**Comment by sergei-sss** [comment]
Hello @AndyJAllen ,
We could not reproduce this problem on Magento 2.3.1 + ElasticSearch v6.8.1 + SearchSuitAutoComplete v2.1.7.
Could you please submit a support ticket [here](https://mageworx.zendesk.com/hc/en-us/requests/new) if you still experience this problem?

**Comment by sergei-sss** [comment]
@AndyJAllen 
Try to use 2.1.8 version pls.
