### ISSUE TITLE
Not working with ElasticSearch 6.5.4 with Searchsuite 2.1.7

### ISSUE THREAD

**Issue by prathap2406** [mageworx/search-suite-autocomplete#5]
This extension is not working with ElasticSearch version 6.5.4 and Magento 2.3.2 with MageWorx_SearchSuiteAutocomplete version 2.1.7 . Kindly do fix this for the future use.
Thanks

**Comment by sergei-sss** [comment]
@prathap2406 
Can you provide more information?
Does magento search work on the search page?

**Comment by prathap2406** [comment]
@sergei-sss 
Yes, magento search is working and even searchsuite is working when we configure mysql in backend instead of ElasticSearch.

**Comment by prathap2406** [comment]
@sergei-sss 
We've been and being using MageWorx_SearchSuiteAutocomplete for our site. It was working fine in Magento 2.3 with ES but once we upgrated our magento to 2.3.2 with elastic search version 6.5.4 it is not working anymore. We went ahead and debugged and we found that is not returning product data but it does return size of the collection with ES. Looking forwarded to here from you soon.

Resutl['data'] is empty

{"result":[{"code":"suggest","data":[{"title":"figma","num_results":"7","url":"https:\/\/m23.localhost\/us\/catalogsearch\/result\/?q=figma"}]},{"code":"product","data":[],"size":7,"url":"https:\/\/m23.localhost.com\/us\/catalogsearch\/result\/?q=test"}]}

**Comment by sergei-sss** [comment]
@prathap2406 
I've added the fix here:
https://github.com/mageworx/search-suite-autocomplete/tree/elastic_search6_compatibility
(only MageWorx/SearchSuiteAutocomplete/Model/Search/Product.php was changed)

Can you pls check it on your side?

**Comment by prathap2406** [comment]
@sergei-sss 
Yes, it does working fine for us now. 
Thanks for your support.
